<?xml version="1.0" encoding="utf-8"?><Database Name="smarTinternDataBase" Class="smarTInternDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=CATIX-PC;Initial Catalog=smarTinternDataBase;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="smarTinternDataBaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ApplicationTable" Member="ApplicationTables">
    <Type Name="ApplicationTable">
      <Column Name="App_Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AppName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description_Id" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="ApplicationTable_Picture" Member="Pictures" ThisKey="App_Id" OtherKey="App_Id" Type="Picture" />
      <Association Name="ApplicationTable_TeamTable" Member="TeamTables" ThisKey="App_Id" OtherKey="App_Id" Type="TeamTable" />
      <Association Name="Description_ApplicationTable" Member="Description" ThisKey="Description_Id" OtherKey="DescriptionId" Type="Description" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Membership" Member="aspnet_Memberships">
    <Type Name="aspnet_Membership">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordFormat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PasswordSalt" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="MobilePIN" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="LoweredEmail" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordQuestion" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordAnswer" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="IsApproved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLockedOut" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastPasswordChangedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLockoutDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAttemptCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAttemptWindowStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAnswerAttemptCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAnswerAttemptWindowStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="aspnet_Membership_TeamTable" Member="TeamTable" ThisKey="UserId" OtherKey="TeamId" Type="TeamTable" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.Description" Member="Descriptions">
    <Type Name="Description">
      <Column Name="DescriptionId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DescriptionPath" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DescriptionName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Description_ApplicationTable" Member="ApplicationTables" ThisKey="DescriptionId" OtherKey="Description_Id" Type="ApplicationTable" />
    </Type>
  </Table>
  <Table Name="dbo.Picture" Member="Pictures">
    <Type Name="Picture">
      <Column Name="PictureId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PictureName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PicturePath" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="App_Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="ApplicationTable_Picture" Member="ApplicationTable" ThisKey="App_Id" OtherKey="App_Id" Type="ApplicationTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StudentTable" Member="StudentTables">
    <Type Name="StudentTable">
      <Column Name="StudentId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="University" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UniversitySection" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Team_Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="TeamTable_StudentTable" Member="TeamTable" ThisKey="Team_Id" OtherKey="TeamId" Type="TeamTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TeamTable" Member="TeamTables">
    <Type Name="TeamTable">
      <Column Name="TeamId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="App_Id" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="TeamTable_StudentTable" Member="StudentTables" ThisKey="TeamId" OtherKey="Team_Id" Type="StudentTable" />
      <Association Name="ApplicationTable_TeamTable" Member="ApplicationTable" ThisKey="App_Id" OtherKey="App_Id" Type="ApplicationTable" IsForeignKey="true" />
      <Association Name="aspnet_Membership_TeamTable" Member="aspnet_Membership" ThisKey="TeamId" OtherKey="UserId" Type="aspnet_Membership" IsForeignKey="true" />
    </Type>
  </Table>
</Database>